name: van_damage_tracker
description: A simple van fleet management application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  supabase_flutter: ^2.5.6
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.1.12
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  uuid: ^4.1.0
  provider: ^6.0.5
  intl: ^0.20.2
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env 