name: van_damage_tracker
description: A van fleet management application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.0.0
  provider: ^6.0.5
  flutter_dotenv: ^5.0.2
  photo_view: ^0.14.0
  image_picker: ^1.0.4
  intl: ^0.18.0
  path: ^1.8.3
  shared_preferences: ^2.2.0
  cached_network_image: ^3.3.0
  url_launcher: ^6.1.14
  uuid: ^4.0.0
  logger: ^2.0.2
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env 